apiVersion: v1
kind: ConfigMap
metadata:
  namespace: blog-ni-system
  name: blog-ni-config
data:
  HUGO_BRANCH: "master"
  HUGO_REPOSITORY: "git@10.43.100.110:sblake/Nightmares.git"
  HUGO_ARGS: "-F --baseURL https://nightmares.technically.fun/"
