apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-provisioner-config
  namespace: nfs-provisioner
data:
  nfs-server: "fileshare"
  nfs-path: "/mnt"
