apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-hot-storage
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner 
parameters:
  server: fileshare
  path: /mnt/hot
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-cold-storage
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner 
parameters:
  server: fileshare
  path: /mnt/cold
reclaimPolicy: Retain
