apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-hot-storage
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner-hot 
parameters:
  pathPattern: "/"
reclaimPolicy: Retain
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-cold-storage
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner-cold
parameters:
  pathPattern: "/"
reclaimPolicy: Retain
