apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: passbolt-app
  name: passbolt-db-pvc
  namespace: passbolt-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi