apiVersion: v1
kind: ConfigMap
metadata:
  namespace: blog-tf-system
  name: blog-tf-after-deploy-config
data:
  after-deploy.sh: |
    #!/bin/ash

    curl --location --request PATCH 'https://192.168.0.6:6443/apis/apps/v1/namespaces/blog-tf-system/statefulsets/blogs-tf-app?fieldManager=kubectl-rollout&pretty=true' \
    --header 'Content-Type: application/strategic-merge-patch+json' \
    --header "Authorization: Bearer $HUGO_KUBECTL_TOKEN" \
    --data-raw '{
        "spec": {
            "template": {
                "metadata": {
                    "annotations": {
                        "kubectl.kubernetes.io/restartedAt": <time.Now()>
                    }
                }
            }
        }
    }'