apiVersion: batch/v1
kind: CronJob
metadata:
  name: blog-tf-rebuild-job
  namespace: blog-tf-system
spec:
  # Run daily at 1AM
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rebuild
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - content="Content-Type: "application/json"
            - secret="X-Gitlab-Token: $(HUGO_PUSH_SECRET)"
            - repository = "{ \"clone_url\": \"$(CRONJOB_REPOSITORY)\" }"
            - data="{ \"ref\": \"$(HUGO_BRANCH)\", \"repository\": $(repository) }"
            - curl -x POST -H $content -H $secret -d $data 10.43.100.100:9000/hooks/build
            volumeMounts:
            - name: blog-tf-timezone-host
              mountPath: /etc/timezone
              readOnly: true
            - name: blog-tf-localtime-host
              mountPath: /etc/localtime
              readOnly: true
            envFrom:
            - secretRef:
                name: blog-tf-secrets
            - configMapRef:
                name: blog-tf-config
          restartPolicy: OnFailure
          volumes:
          - name: blog-tf-timezone-host
            hostPath:
              path: /etc/timezone
              type: File
          - name: blog-tf-localtime-host
            hostPath:
              path: /etc/localtime
              type: File
