apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-tf-ingress
  namespace: blog-tf-system
spec:
  ingressClassName: nginx-external
  rules:
  - host: blog.technically.fun
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog-tf-svc
            port:
              number: 80