apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: blog-tf-app
  name: blog-tf-static-pvc
  namespace: blog-tf-system
spec:
  storageClassName: nfs-cold-storage
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: blog-tf-app
  name: blog-tf-www-pvc
  namespace: blog-tf-system
spec:
  storageClassName: nfs-cold-storage
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: blog-tf-app
  name: blog-tf-gogs-ssh-pvc
  namespace: blog-tf-system
spec:
  storageClassName: nfs-cold-storage
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi


        
