apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex-app
  name: plex-config-pvc
  namespace: plex-system
  annotations:
    nfs.io/storage-path: "programs/plex/config"
spec:
  storageClassName: nfs-cold-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex-app
  name: plex-transcode-pvc
  namespace: plex-system
  annotations:
    nfs.io/storage-path: "programs/plex/transcode"
spec:
  storageClassName: nfs-hot-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex-app
  name: plex-data-pvc
  namespace: plex-system
  annotations:
    nfs.io/storage-path: "programs/plex/data"
spec:
  storageClassName: nfs-cold-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: plex-app
  name: plex-library-pvc
  namespace: plex-system
  annotations:
    nfs.io/storage-path: "media"
spec:
  storageClassName: nfs-cold-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
