apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex-app
  namespace: plex-system
spec:
  serviceName: plex-app-svc
  replicas: 1
  selector:
    matchLabels:
      app: plex-app
  template:
    metadata:
      labels:
        app: plex-app
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name: plex
          image: plexinc/pms-docker:1.24.1.4931-1a38e63c6
          ports:
            - containerPort: 32400
              protocol: TCP
            - containerPort: 3005
              protocol: TCP
            - containerPort: 8324
              protocol: TCP
            - containerPort: 32469
              protocol: TCP
            - containerPort: 1900
              protocol: UDP
            - containerPort: 32410
              protocol: UDP
            - containerPort: 32412
              protocol: UDP
            - containerPort: 32413
              protocol: UDP
            - containerPort: 32414
              protocol: UDP
          volumeMounts:
            - name: plex-config-pvc
              mountPath: /config
            - name: plex-transcode-pvc
              mountPath: /transcode
            - name: plex-data-pvc
              mountPath: /data
          envFrom:
            - secretRef:
                name: plex-secrets
            - configMapRef:
                name: plex-config
        - name: samba
          image: stanback/alpine-samba
          ports:
            - containerPort: 445
          volumeMounts:
            - name: plex-data-pvc
              mountPath: /share
            - name: plex-samba-config-volume
              mountPath: /etc/samba/smb.conf
              subPath: smb.conf
      volumes:
      - name: plex-config-pvc
        persistentVolumeClaim:
          claimName: plex-config-pvc
      - name: plex-transcode-pvc
        persistentVolumeClaim:
          claimName: plex-transcode-pvc
      - name: plex-data-pvc
        persistentVolumeClaim:
          claimName: plex-data-pvc
      - name: plex-samba-config-volume
        configMap:
          name: plex-samba-config