apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tzi-app
  name: tzi-static-pvc
  namespace: tzi-system
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tzi-app
  name: tzi-www-pvc
  namespace: tzi-system
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tzi-app
  name: tzi-gogs-ssh-pvc
  namespace: tzi-system
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi


        