apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: technically-fun-ingress
  namespace: technically-fun-system
spec:
  ingressClassName: nginx-external
  rules:
  - host: technically.fun
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: technically-fun-svc
            port:
              number: 80