apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: technically-fun-app
  name: technically-fun-pvc
  namespace: technically-fun-system
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
