apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: vaultwarden-app
  name: vaultwarden-pvc
  namespace: vaultwarden-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi