apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: vaultwarden-app
  name: vaultwarden-pvc
  namespace: vaultwarden-system
  annotations:
    nfs.io/storage-path: "programs/vaultwarden"
spec:
  storageClassName: nfs-cold-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
