apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-svc
  namespace: vaultwarden-system
  labels:
    app: vaultwarden-svc
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: vaultwarden-app