apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-ingress
  namespace: qbittorrent-system
spec:
  ingressClassName: nginx-internal
  rules:
  - host: tor.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qbittorrent-svc
            port:
              number: 8080