apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-pvc
  namespace: qbittorrent-system
  labels:
    app: qbittorrent-app
  annotations:
    nfs.io/storage-path: "programs/qbittorrent"
spec:
  storageClassName: nfs-cold-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: qbittorrent-app
  name: qbittorrent-downloads-pvc
  namespace: qbittorrent-system
  annotations:
    nfs.io/storage-path: "Media"
spec:
  storageClassName: nfs-cold-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
