apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorent-config-pvc
  namespace: qbittorent-system
  labels:
    app: qbittorent-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: qbittorent-app
  name: qbittorent-downloads-pvc
  namespace: qbittorent-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti