apiVersion: v1
kind: ConfigMap
metadata:
  namespace: blog-kc-system
  name: blog-kc-curl-trigger-config
data:
  curl-trigger.sh: |
    #!/bin/ash

    curl -L -X POST '10.43.100.101:9000/hooks/build' \
    -H 'Content-Type: application/json' \
    --insecure \
    -d "{
        \"ref\" : \"$HUGO_BRANCH\",
        \"secret\": \"$HUGO_PUSH_SECRET\",
        \"repository\": {
            \"clone_url\": \"$CRONJOB_REPOSITORY\"
        }
    }"