apiVersion: batch/v1
kind: CronJob
metadata:
  name: blog-kc-rebuild-job
  namespace: blog-kc-system
spec:
  # Run daily at 1AM
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rebuild
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl 10.43.100.101:9000/hooks/build
            volumeMounts:
            - name: blog-kc-timezone-host
              mountPath: /etc/timezone
              readOnly: true
            - name: blog-kc-localtime-host
              mountPath: /etc/localtime
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: blog-kc-timezone-host
            hostPath:
              path: /etc/timezone
              type: File
          - name: blog-kc-localtime-host
            hostPath:
              path: /etc/localtime
              type: File