apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: blog-kc-app
  name: blog-kc-static-pvc
  namespace: blog-kc-system
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: blog-kc-app
  name: blog-kc-www-pvc
  namespace: blog-kc-system
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: blog-kc-app
  name: blog-kc-gogs-ssh-pvc
  namespace: blog-kc-system
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
