apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog-kc-sa
  namespace: blog-kc-system
automountServiceAccountToken: true
secrets:
- name: blog-kc-sa-secret
---

apiVersion: v1
kind: Secret
metadata:
  name: blog-kc-sa-secret
  namespace: blog-kc-system
  annotations:
    kubernetes.io/service-account.name: blog-kc-sa
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: blog-kc-system
  name: blog-kc-deployment-role
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["patch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: blog-kc-system
  name: blog-kc-deployment-rolebinding
subjects:
- kind: ServiceAccount
  name: blog-kc-sa
  namespace: blog-kc-system
roleRef:
  kind: Role
  name: blog-kc-deployment-role
  apiGroup: rbac.authorization.k8s.io