apiVersion: v1
kind: Service
metadata:
  name: samba-lb
  namespace: samba-system
spec:
  selector:
    app: samba-app
  type: LoadBalancer
  loadBalancerIP: 192.168.0.252
  ports:
    - port: 445
      targetPort: 445