apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: samba-app
  name: samba-pvc
  namespace: samba-system
spec:
  storageClassName: nfs-cold-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5.5Ti
