apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gogs-app
  name: gogs-data-pvc
  namespace: gogs-system
spec:
  storageClassName: nfs-cold-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
