apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: code-server-app
  name: code-server-config-pvc
  namespace: code-server-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: code-server-app
  name: code-server-data-pvc
  namespace: code-server-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti