apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kavita-app
  name: kavita-config-pvc
  namespace: kavita-system
  annotations:
    nfs.io/storage-path: "programs/kavita"
spec:
  storageClassName: nfs-cold-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kavita-app
  name: kavita-library-pvc
  namespace: kavita-system
  annotations:
    nfs.io/storage-path: "media"
spec:
  storageClassName: nfs-cold-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
