apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kavita-app
  name: kavita-config-pvc
  namespace: kavita-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kavita-app
  name: kavita-library-pvc
  namespace: kavita-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti