apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config-pvc
  namespace: frigate-system
  labels:
    app: frigate-app
  annotations:
    nfs.io/storage-path: "programs/frigate"
spec:
  storageClassName: nfs-cold-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: frigate-app
  name: frigate-storage-pvc
  namespace: frigate-system
  annotations:
    nfs.io/storage-path: "security-footage"
spec:
  storageClassName: nfs-cold-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
