apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: postgresql-system
  labels:
    app: postgresql-db
spec:
  storageClassName: nfs-hot-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
