apiVersion: v1
kind: ConfigMap
metadata:
  namespace: gitea-system
  name: gitea-config
data:
  GITEA__database__DB_TYPE: postgres
  GITEA__database__HOST: 192.168.0.251:5432
  GITEA__database__NAME: giteadb
  GITEA__database__USER: gitea