apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gitea-app
  name: gitea-data-pvc
  namespace: gitea-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi