apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  namespace: nextcloud-system
  annotations:
    kubernetes.io/ingress.class: nginx-exposed
spec:
  rules:
  - host: cloud.heyit.works
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud-svc
            port:
              number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress-internal
  namespace: nextcloud-system
  annotations:
    kubernetes.io/ingress.class: nginx-internal
spec:
  rules:
  - host: cloud.home
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud-svc
            port:
              number: 80