apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nextcloud-app
  name: nextcloud-web-pvc
  namespace: nextcloud-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi