apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: wireguard-app
  name: wireguard-pvc
  namespace: wireguard-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi