apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: parry-app
  name: parry-pvc
  namespace: parry-system
  annotations:
    nfs.io/storage-path: "programs/parry"
spec:
  storageClassName: nfs-cold-storage
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
